<?php

namespace LifeHax\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionRepository extends EntityRepository
{
}
