<?php

namespace LifeHax\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResumeRepository extends EntityRepository
{
}
