<?php

namespace LifeHax\HaxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HaxImgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HaxImgRepository extends EntityRepository
{
}
