<?php

namespace LifeHax\HaxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HaxStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HaxStepRepository extends EntityRepository
{
}
