<?php

namespace LifeHax\HaxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HaxTxtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HaxTxtRepository extends EntityRepository
{
}
