<?php

namespace LifeHax\HaxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HaxVidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HaxVidRepository extends EntityRepository
{
}
