<?php

namespace LifeHax\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreationRepository extends EntityRepository
{
}
